diccionario_orange = {
    'fbb_conv': ['FBB Convergencia',
                 {
                     4: 'fbb_conv_doble_capta',
                     5: 'fbb_conv_x_sell'
                 }],
    'fbb_only': ['FBB Stand Alone',
                 {
                     0: 'fbb_only'
                 }],
    'mov_conv': ['Móvil Convergencia',
                 {
                     5: 'mov_conv_1as_lineas',
                     8: 'mov_conv_2as_lineas',
                     11: 'mov_conv_doble_capta',
                     14: 'mov_conv_x_sell',
                     17: 'mov_conv_ampliaciones'
                 }],
    'mov_only': ['Mobile Only',
                 {
                     3: 'mov_only_voice_data',
                     6: 'mov_only_data',
                     7: 'mov_only_4G',
                     8: 'mov_only_mi_fijo',
                 }],
    'mix_canal': ['Mix canal Osp',
                  {
                      3: 'mix_fbb_vtas_exclusivo_ttpp',
                      5: 'mix_fbb_vtas_exclusivo_franq',
                      6: 'mix_fbb_vtas_exclusivo_resto',
                      8: 'mix_fbb_vtas_eshop_tw',
                      9: 'mix_fbb_vtas_eshop_web_online',
                      11: 'mix_fbb_vtas_plataformas_inbound',
                      12: 'mix_fbb_vtas_plataformas_outbound',
                      16: 'mix_fbb_vtas_plataformas_resto',
                      17: 'mix_fbb_vtas_no_exclusivo',
                      18: 'mix_fbb_vtas_resto',
                      19: 'mix_fbb_vtas_salesforce',
                      22: 'mix_fbb_op_retencion',
                      23: 'mix_fbb_op_fidelizacion',
                      24: 'mix_fbb_op_resto',
                      28: 'mix_mov_vtas_no_exclusivo_phone_house',
                      29: 'mix_mov_vtas_no_exclusivo_ggss',
                      30: 'mix_mov_vtas_no_exclusivo_resto',
                      32: 'mix_mov_vtas_exclusivo_ttpp',
                      33: 'mix_mov_vtas_exclusivo_franquicia',
                      34: 'mix_mov_vtas_exclusivo_resto',
                      36: 'mix_mov_vtas_plataformas_inbound',
                      37: 'mix_mov_vtas_plataformas_outbound',
                      39: 'mix_mov_vtas_eshop_eshop',
                      40: 'mix_mov_vtas_eshop_tw',
                      42: 'mix_mov_op_total'
                  }],
    'mix_squad': ['Mix_Squad',
                  {
                      2: 'fbb_presenciales_tiendas',
                      3: 'fbb_presenciales_stands',
                      4: 'fbb_presenciales_canal_no_exclusivo',
                      5: 'fbb_presenciales_canal_alternativo',
                      7: 'fbb_online_tol',
                      8: 'fbb_online_ccc_cartera',
                      10: 'fbb_new_customer_dist_online',
                      11: 'fbb_new_customer_tw',
                      12: 'fbb_new_customer_emision_online',
                      13: 'fbb_new_customer_inbound',
                      14: 'fbb_new_customer_outbound',
                      16: 'fbb_commercial_funnel_cancelaciones',
                      18: 'fbb_cartera_inbound',
                      19: 'fbb_cartera_outbound_cross_sell',
                      20: 'fbb_cartera_tw',
                      22: 'fbb_loyalty_inbound_anticipacion',
                      23: 'fbb_loyalty_outbound_anticipacion',
                      24: 'fbb_loyalty_inbound_fidelizacion',
                      25: 'fbb_loyalty_outbound_fidelizacion',
                      26: 'fbb_loyalty_cdom',
                      28: 'fbb_retencion_voluntarias',
                      29: 'fbb_retencion_portabilidad',
                      31: 'fbb_resto',
                      64: 'mov_presenciales_tiendas',
                      65: 'mov_presenciales_stands',
                      66: 'mov_presenciales_canal_no_exclusivo',
                      67: 'mov_presenciales_canal_alternativo',
                      69: 'mov_online_tol',
                      72: 'mov_new_customer_dist_online',
                      73: 'mov_new_customer_tw',
                      74: 'mov_new_customer_emision_online',
                      75: 'mov_new_customer_inbound',
                      76: 'mov_new_customer_outbound',
                      78: 'mov_commercial_funnel_cancelaciones',
                      80: 'mov_cartera_inbound',
                      81: 'mov_cartera_outbound_cross_sell',
                      82: 'mov_cartera_tw',
                      84: 'mov_loyalty_inbound_anticipacion',
                      85: 'mov_loyalty_outbound_anticipacion',
                      86: 'mov_loyalty_inbound_fidelizacion',
                      87: 'mov_loyalty_outbound_fidelizacion',
                      90: 'mov_retencion_voluntarias',
                      91: 'mov_retencion_portabilidad',
                      93: 'mov_resto'
                  }]
}
