diccionario_orange = {
    'total_orange':['Orange',
             {
                 3:'osp_fbb_convergencia',
                 9:'osp_fbb_stand_alone',
                 49:'osp_mov_convergencia',
                 67:'osp_mov_only',
                 47:'LTE'
                 }],
    'total_amena':['Mix canal Amena',
            {
                0:'amena_fbb',
                26:'amena_mov'
            }],
    'fbb_conv': ['FBB Convergencia',
                 {
                     4: 'fbb_conv_doble_capta',
                     5: 'fbb_conv_x_sell'
                 }],
    'fbb_only': ['FBB Stand Alone',
                 {
                     0: 'fbb_only'
                 }],
    'mov_conv': ['Móvil Convergencia',
                 {
                     5: 'mov_conv_1as_lineas',
                     8: 'mov_conv_2as_lineas',
                     11: 'mov_conv_doble_capta',
                     14: 'mov_conv_x_sell',
                     17: 'mov_conv_ampliaciones'
                 }],
    'mov_only': ['Mobile Only',
                 {
                     3: 'mov_only_voice_data',
                     6: 'mov_only_data',
                     7: 'mov_only_4G',
                     8: 'mov_only_mi_fijo',
                 }],
    'mix_canal': ['Mix canal Osp',
                  {
                      3: 'mix_fbb_vtas_exclusivo_ttpp',
                      5: 'mix_fbb_vtas_exclusivo_franq',
                      6: 'mix_fbb_vtas_exclusivo_resto',
                      8: 'mix_fbb_vtas_eshop_tw',
                      9: 'mix_fbb_vtas_eshop_web_online',
                      11: 'mix_fbb_vtas_plataformas_inbound',
                      12: 'mix_fbb_vtas_plataformas_outbound',
                      16: 'mix_fbb_vtas_plataformas_resto',
                      17: 'mix_fbb_vtas_no_exclusivo',
                      18: 'mix_fbb_vtas_resto',
                      19: 'mix_fbb_vtas_salesforce',
                      22: 'mix_fbb_op_retencion',
                      23: 'mix_fbb_op_fidelizacion',
                      24: 'mix_fbb_op_resto',
                      28: 'mix_mov_vtas_no_exclusivo_phone_house',
                      29: 'mix_mov_vtas_no_exclusivo_ggss',
                      30: 'mix_mov_vtas_no_exclusivo_resto',
                      32: 'mix_mov_vtas_exclusivo_ttpp',
                      33: 'mix_mov_vtas_exclusivo_franquicia',
                      34: 'mix_mov_vtas_exclusivo_resto',
                      36: 'mix_mov_vtas_plataformas_inbound',
                      37: 'mix_mov_vtas_plataformas_outbound',
                      39: 'mix_mov_vtas_eshop_eshop',
                      40: 'mix_mov_vtas_eshop_tw',
                      42: 'mix_mov_op_total'
                  }],
    'mix_squad': ['Mix_Squad',
                  {
                      2: 'fbb_presenciales_tiendas',
                      3: 'fbb_presenciales_stands',
                      4: 'fbb_presenciales_canal_no_exclusivo',
                      5: 'fbb_presenciales_canal_alternativo',
                      7: 'fbb_online_tol',
                      8: 'fbb_online_ccc_cartera',
                      10: 'fbb_new_customer_dist_online',
                      11: 'fbb_new_customer_tw',
                      12: 'fbb_new_customer_emision_online',
                      13: 'fbb_new_customer_inbound',
                      14: 'fbb_new_customer_outbound',
                      16: 'fbb_commercial_funnel_cancelaciones',
                      18: 'fbb_cartera_inbound',
                      19: 'fbb_cartera_outbound_cross_sell',
                      20: 'fbb_cartera_tw',
                      23: 'fbb_loyalty_inbound_anticipacion',
                      24: 'fbb_loyalty_outbound_anticipacion',
                      25: 'fbb_loyalty_inbound_fidelizacion',
                      27: 'fbb_loyalty_outbound_fidelizacion',
                      30: 'fbb_loyalty_cdom',
                      32: 'fbb_retencion_voluntarias',
                      33: 'fbb_retencion_portabilidad',
                      35: 'fbb_resto',
                      68: 'mov_presenciales_tiendas',
                      69: 'mov_presenciales_stands',
                      70: 'mov_presenciales_canal_no_exclusivo',
                      71: 'mov_presenciales_canal_alternativo',
                      73: 'mov_online_tol',
                      74: 'mov_online_ccc_cartera',
                      76: 'mov_new_customer_dist_online',
                      77: 'mov_new_customer_tw',
                      78: 'mov_new_customer_emision_online',
                      79: 'mov_new_customer_inbound',
                      80: 'mov_new_customer_outbound',
                      82: 'mov_commercial_funnel_cancelaciones',
                      84: 'mov_cartera_inbound',
                      85: 'mov_cartera_outbound_cross_sell',
                      86: 'mov_cartera_tw',
                      89: 'mov_loyalty_inbound_anticipacion',
                      90: 'mov_loyalty_outbound_anticipacion',
                      91: 'mov_loyalty_inbound_fidelizacion',
                      93: 'mov_loyalty_outbound_fidelizacion',
                      97: 'mov_retencion_voluntarias',
                      98: 'mov_retencion_portabilidad',
                      100: 'mov_resto'
                  }],
    'mix_orange_2':[
        'Mix canal Osp',
        {
        2: 'mix_fbb_eshop_online',
        3: 'mix_fbb_eshop_distributors',
        4: 'mix_fbb_operations_total',
        5: 'mix_fbb_other_total',
        7: 'mix_fbb_retail_alternative',
        8: 'mix_fbb_retail_dho',
        9: 'mix_fbb_retail_exclusive',
        10: 'mix_fbb_retail_frc',
        11: 'mix_fbb_retail_non_excl_eci',
        12: 'mix_fbb_retail_non_excl_others',
        13: 'mix_fbb_retail_non_excl_ggss',
        14: 'mix_fbb_retail_non_exclusibe_tph',
        15: 'mix_fbb_retail_others',
        16: 'mix_fbb_retail_ttpp',
        17: 'mix_fbb_telesales_in',
        18: 'mix_fbb_telesales_out',
        19: 'mix_fbb_teleweb_total',
        28: 'mix_mov_eshop_online',
        29: 'mix_mov_eshop_distributors',
        30: 'mix_mov_operations_total',
        31: 'mix_mov_other_total',
        33: 'mix_mov_retail_alternative',
        34: 'mix_mov_retail_dho',
        35: 'mix_mov_retail_exclusive',
        36: 'mix_mov_retail_frc',
        37: 'mix_mov_retail_non_excl_eci',
        38: 'mix_mov_retail_non_excl_others',
        39: 'mix_mov_retail_non_excl_ggss',
        40: 'mix_mov_retail_non_exclusibe_tph',
        41: 'mix_mov_retail_others',
        42: 'mix_mov_retail_ttpp',
        43: 'mix_mov_telesales_in',
        44: 'mix_mov_telesales_out',
        45: 'mix_mov_teleweb_total',

        }
    ]
}


migras_base = {
    "fecha_semana":[],
    "migras":[],
    "file":[]
}